#!/bin/bash
set -x
set -e

RSYNC_OPT=""
[ -n "${INIT_WORLD:-}" ] && RSYNC_OPT=" --delete "

rsync -a $RSYNC_OPT /opt/minecraft/ /minecraft/
cd /minecraft
[ -n "${OPS:-}" ]         && echo "$OPS" > /minecraft/ops.txt
[ -n "${ONLINE_MODE:-}" ] && sed -i -e "s/^online-mode=.*/online-mode=$ONLINE_MODE/g" /minecraft/server.properties

echo "jsp classroom on" | /usr/bin/java -Xmx8192M -Xmx1G -XX:+UseConcMarkSweepGC -classpath sc-mqtt.jar:spigot-1.12.1.jar org.bukkit.craftbukkit.Main
